#Plugin-mode game or setup
plugin-mode: 'setup'
#Database credentials:
database:
  name: ''
  host: ''
  port: ''
  username: ''
  password: ''
lobby:
  world: ''
  x:
  y:
  z:
  pitch:
  yaw:
arena:
  name: ''
  minimumPlayers: ''
  maximumPlayers: ''
  killsToEndGame: ''
  world: ''
  spawn-locations:
    1:
      x:
      y:
      z:
      pitch:
      yaw:
    2:
      x:
      y:
      z:
      pitch:
      yaw:
  powerup-locations:
    1:
      x:
      y:
      z:
      pitch:
      yaw:
game-duration: 30