name: OITC
version: '${project.version}'
main: me.tqqn.oitc.OITC
api-version: 1.16
description: Run, shoot and run, repeat.
depend: [ProtocolLib]
commands:
  start:
    description: Start Command
    usage: /<command>
    permission: oitc.start
  setup:
    description: Setup Command
    usage: /<command>
    permission: oitc.setup.mode
